/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current:     'currentColor',
      bg:     '#0A0A0B',
      s1:     '#111114',
      s2:     '#16161A',
      border: '#1F1F23',
      'border-strong': '#2A2A30',
      text:   '#E6E6E6',
      muted:  '#8A8A93',
      dim:    '#5A5A63',
      accent: '#E89B2C',
      up:     '#1FBF75',
      down:   '#E5484D',
      warn:   '#D4A017',
      info:   '#3B82F6',
      white:  '#FFFFFF',
      black:  '#000000',
    },
    fontFamily: {
      mono: ['"IBM Plex Mono"', 'ui-monospace', 'Consolas', 'monospace'],
    },
    fontSize: {
      '2xs': ['11px', { lineHeight: '1.3' }],
      xs:    ['12px', { lineHeight: '1.3' }],
      sm:    ['13px', { lineHeight: '1.4' }],
      base:  ['14px', { lineHeight: '1.4' }],
      md:    ['16px', { lineHeight: '1.3' }],
      lg:    ['20px', { lineHeight: '1.3' }],
    },
    spacing: {
      px:  '1px',
      0:   '0px',
      0.5: '2px',
      1:   '4px',
      1.5: '6px',
      2:   '8px',
      3:   '12px',
      4:   '16px',
      6:   '24px',
      8:   '32px',
      10:  '40px',
      12:  '48px',
      16:  '64px',
      20:  '80px',
      24:  '96px',
    },
    borderRadius: {
      DEFAULT: '0px',
      sm: '2px',
      full: '9999px',
    },
    extend: {},
  },
  plugins: [],
}

