/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      current:     'currentColor',
      bg:     'var(--color-bg)',
      s1:     'var(--color-s1)',
      s2:     'var(--color-s2)',
      border: 'var(--color-border)',
      'border-strong': 'var(--color-border-strong)',
      text:   'var(--color-text)',
      muted:  'var(--color-muted)',
      dim:    'var(--color-dim)',
      accent: 'var(--color-accent)',
      up:     '#1FBF75',
      down:   '#E5484D',
      warn:   '#D4A017',
      info:   '#3B82F6',
      white:  '#FFFFFF',
      black:  '#000000',
    },
    fontFamily: {
      sans: ['"Lato"', 'sans-serif'],
    },
    fontSize: {
      '2xs': ['0.82rem', { lineHeight: '1.3' }],
      xs:    ['0.94rem', { lineHeight: '1.3' }],
      sm:    ['1rem', { lineHeight: '1.4' }],
      base:  ['1.06rem', { lineHeight: '1.4' }],
      md:    ['1.24rem', { lineHeight: '1.3' }],
      lg:    ['1.53rem', { lineHeight: '1.25' }],
      xl:    ['1.82rem', { lineHeight: '1.2' }],
      '2xl': ['2.12rem', { lineHeight: '1.15' }],
      '3xl': ['2.59rem', { lineHeight: '1.1' }],
      '4xl': ['3.18rem', { lineHeight: '1.05' }],
      '5xl': ['3.76rem', { lineHeight: '1.02' }],
      '6xl': ['4.47rem', { lineHeight: '1' }],
      '7xl': ['5.41rem', { lineHeight: '0.98' }],
    },
    spacing: {
      px:  '1px',
      0:   '0px',
      0.5: '2px',
      1:   '4px',
      1.5: '6px',
      2:   '8px',
      3:   '12px',
      4:   '16px',
      6:   '24px',
      8:   '32px',
      10:  '40px',
      12:  '48px',
      16:  '64px',
      20:  '80px',
      24:  '96px',
    },
    borderRadius: {
      DEFAULT: '0px',
      sm: '2px',
      full: '9999px',
    },
    extend: {},
  },
  plugins: [],
}
